### ISSUE TITLE
P. Engine for Detecting Alerts

### ISSUE THREAD

**Issue by MoisesAdame** [TC3005B-562-2024/Spring-Boot-Backend#131]
**Details**
An engine that runs while the backend is running and checks the metrics of all the Routing Profiles, Queues and Agents of the instance. If an alert threshold is met, save it in the database. 

**Tasks / Tareas por hacer**
- [x] Create a Procedure that runs every second (while the backend is active)
- [x] Request Metrics for all the Routing Profiles, Queues and Agents of the instance
- [x] Create a function that checks every metric and launches a new alert if a certain threshold is met.
